env:
  - LANG=zh_CN.UTF-8
language: python
sudo: false

cache:
  - pip
  directories:
    - .doit.db.bak
    - .doit.db.dat
    - .doit.db.dir
    - $HOME/output
    - $HOME/cache
    - $HOME/__pycache__

git:
  depth: 3

branches:
  only:
    - src

python:
  - 3.7

install:
  - pip install 'Nikola[extras]'

script:
  - nikola build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  local_dir: output
  target_branch: master
  on:
    branch: src

notifications:
  email:
    recipients:
      - ashfinal@sina.cn
    on_success: never
    on_failure: always

# vim:set nowrap et sw=2 ts=2:
