language: python
cache:
  - pip
sudo: false

branches:
  only:
    - src

python:
  - 3.7

install:
  - pip install 'Nikola[extras]'

script:
  - nikola build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  local_dir: output
  target_branch: master
  on:
    branch: src

notifications:
  email:
    on_success: change
    on_failure: always

# vim:set nowrap et sw=2 ts=2:
