env:
  - LANG=zh_CN.UTF-8
language: python
sudo: false

cache:
  directories:
  - $HOME/.cache/pip

git:
  depth: 3

branches:
  only:
    - src

python:
  - 3.7

install:
  - pip install 'Nikola[extras]'

script:
  - nikola build
  - find $HOME/output/galleries -type f -name "*.thumbnail.*" -delete
  - nikola build -a render_galleries # Don't know why galleries task fails, so we run it once manually.

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  local_dir: output
  target_branch: master
  on:
    branch: src

notifications:
  email:
    recipients:
      - ashfinal@sina.cn
    on_success: never
    on_failure: always

# vim:set nowrap et sw=2 ts=2:
