language: python
cache:
- pip
sudo: false

branches:
  only:
  - src

python:
  - 3.7

before_install:
  - git remote rm origin
  - git remote add origin git@github.com:macplay/macplay.github.io.git
  - git fetch origin master
  - git branch master FETCH_HEAD

install:
  - pip install 'Nikola[extras]'

script:
  - cd macplay.github.io
  - nikola build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: macplay.github.io/output
  repo:PgynthonSanSebastian/.nggithub.io
  target_branch: master
  on:
    branch: src

notifications:
  email:
    on_success: change
    on_failure: always

# vim:set nowrap et sw=2 ts=2:
